/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceGrafica;

/**
 *
 * @author Thairam Michel
 */
public class FrameMainScreen extends javax.swing.JFrame {

    /**
     * Creates new form FrameMainScreen
     */
    public FrameMainScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMClientes = new javax.swing.JMenu();
        jMCadastrarCliente = new javax.swing.JMenuItem();
        jMListarClientes = new javax.swing.JMenuItem();
        jMCheques = new javax.swing.JMenu();
        jMCadastrarCheque = new javax.swing.JMenuItem();
        jMListarCheques = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem8.setText("jMenuItem8");

        jMenuItem9.setText("jMenuItem9");

        jMenuItem10.setText("jMenuItem10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setExtendedState(6);

        jDesktopPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1130, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 783, Short.MAX_VALUE)
        );

        jMenuBar1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(80, 42));

        jMClientes.setBorder(null);
        jMClientes.setText("Clientes");
        jMClientes.setPreferredSize(new java.awt.Dimension(80, 40));
        jMClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMClientesActionPerformed(evt);
            }
        });

        jMCadastrarCliente.setText("Cadastrar Cliente");
        jMCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCadastrarClienteActionPerformed(evt);
            }
        });
        jMClientes.add(jMCadastrarCliente);

        jMListarClientes.setText("Listar Clientes");
        jMListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMListarClientesActionPerformed(evt);
            }
        });
        jMClientes.add(jMListarClientes);

        jMenuBar1.add(jMClientes);

        jMCheques.setBorder(null);
        jMCheques.setText("Cheques");

        jMCadastrarCheque.setText("Cadastrar Cheque");
        jMCadastrarCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCadastrarChequeActionPerformed(evt);
            }
        });
        jMCheques.add(jMCadastrarCheque);

        jMListarCheques.setText("Listar Cheques");
        jMListarCheques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMListarChequesActionPerformed(evt);
            }
        });
        jMCheques.add(jMListarCheques);

        jMenuBar1.add(jMCheques);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCadastrarClienteActionPerformed
        FrameCadastroCliente cliente = new FrameCadastroCliente();
        cliente.setVisible(true);
    }//GEN-LAST:event_jMCadastrarClienteActionPerformed

    private void jMClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMClientesActionPerformed

    private void jMListarChequesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMListarChequesActionPerformed
        FrameCheques listaCheque = new FrameCheques();
        listaCheque.setVisible(true);
    }//GEN-LAST:event_jMListarChequesActionPerformed

    private void jMCadastrarChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCadastrarChequeActionPerformed
        FrameCadastroCheque cheque = new FrameCadastroCheque();
        cheque.setVisible(true);

    }//GEN-LAST:event_jMCadastrarChequeActionPerformed

    private void jMListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMListarClientesActionPerformed
        FrameCliente cliente = new FrameCliente();
        cliente.setVisible(true);
    }//GEN-LAST:event_jMListarClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuItem jMCadastrarCheque;
    private javax.swing.JMenuItem jMCadastrarCliente;
    private javax.swing.JMenu jMCheques;
    private javax.swing.JMenu jMClientes;
    private javax.swing.JMenuItem jMListarCheques;
    private javax.swing.JMenuItem jMListarClientes;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
